// Generated by Unloop
// Office Thermostat

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_quick_comfort_clicked(|| {
        println!("quick_comfort clicked");
    });
    
    app.on_away_mode_clicked(|| {
        println!("away_mode clicked");
    });
    

    
    app.run()
}
